sudo: required
language: go
services:
  - docker

# Update docker version higher than 17.05
before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

# Build docker image by multi-stage builds
script:
  - docker build -t golang-docker-alpine -f .

# Push minimize image to heroku container registry
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com
  - docker tag golang-docker-alpine registry.heroku.com/golang-docker-alpine/web
  - docker push registry.heroku.com/golang-docker-alpine/web