sudo: required

language: go

services:
  - docker
script:
# build app binary on Alpine OS with golang package
- docker build -t dinos80152/go-docker-alpine-src -f DockerfileSrc .
# Copy app binary from container to host
- docker cp $(docker create dinos80152/go-docker-alpine-src):/go/bin/go-docker-alpine ./
# Build docker image with pure alpine os and app binary
- docker build -t go-docker-alpine -f DockerfileBin .

after_success:
# Push minimize image to heroku container registry
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com
- docker tag go-docker-alpine registry.heroku.com/go-docker-alpine/web
- docker push registry.heroku.com/go-docker-alpine/web

# deploy:
#  provider: heroku
#  api_key:
#    secure: fAXumnO5I+9Cvrxi9AU6z6xe8UAWuk94/AeM1wBZFSq49DcVqj3rwxvgNJ2pJSwUYZX2qBfZhReZ0xqAa5N9n6G8XC7Q6tz0oVUcHK+iJTOSqwyPaaNCUzXrsl0Ru5bt1HQhqzAmssugoa0r5dE8WJlVhuugic9al8yF6waKYE0DRaNwHI/C4IoPtHYnAK+wRd+6yOV5vY644/pCpb70Q67nEyI/hLGZ8EVVZOjHl/BS6BA07K8vbnOMyt3cdDw6RzCAK33KjErMZQ572xG2IXFxZb9goAQSSd+nxgRT//YkjiItxosAkkjM60y6Jy2z/6xszww6OVUBq71mGpObPGA5E6ubEalfICsD45cQ7VZo8AJ7qM6adP8Qihf5UUA5g7hIYAKiyc0XxJjwSzvylL0aTXhy9qnUBHZDento9LhKy+syyg9cANlen+Ww8cNNlyER6DN84pXMN3asQNMMmII1cXaHARfMoIu5k9HR3WOnn1vgTHls3lKHu6pjp8AznHfWep1uP4Y8k9M2gzpslHErlzSO7Z5MagIUByxB/jonBuSf/LaNOeME//+f+7ms2or+jLrGw+hv8Ij6+pTKYllS51BD/f9jdyRNhTVhRsscAm5OIEoH4uLznyVf2tzHVeD2x31rv2uj40F7l3kczdAgL1wbnYY71qdIoIlcxqA=